#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layer_names {
    HOMEROW,
    SYMBOLS,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//    ┌───────────┬───────────┬───────────┬──────────┬──────┐                       ┌──────┬──────────┬───────────┬───────────┬───────────┐
//    │     q     │     w     │     e     │    r     │  t   │                       │  y   │    u     │     i     │     o     │     p     │
//    ├───────────┼───────────┼───────────┼──────────┼──────┤                       ├──────┼──────────┼───────────┼───────────┼───────────┤
//    │ LSFT_T(a) │ LT(5, s)  │ LT(1, d)  │ LT(3, f) │  g   │                       │  h   │ LT(4, j) │ LT(2, k)  │ LT(6, l)  │ LSFT_T(;) │
//    ├───────────┼───────────┼───────────┼──────────┼──────┤                       ├──────┼──────────┼───────────┼───────────┼───────────┤
//    │     z     │ LCTL_T(x) │ LALT_T(c) │    v     │  b   │                       │  n   │    m     │ LALT_T(,) │ LCTL_T(.) │     /     │
//    └───────────┴───────────┴───────────┴──────────┼──────┼──────┐   ┌────────────┼──────┼──────────┴───────────┴───────────┴───────────┘
//                                                   │ kp_0 │ bspc │   │ LT(7, spc) │ kp_1 │
//                                                   └──────┴──────┘   └────────────┴──────┘
[HOMEROW] = LAYOUT_split_3x5_2(
  KC_Q         , KC_W         , KC_E         , KC_R        , KC_T  ,                               KC_Y  , KC_U        , KC_I            , KC_O           , KC_P           ,
  LSFT_T(KC_A) , LT(5, KC_S)  , LT(1, KC_D)  , LT(3, KC_F) , KC_G  ,                               KC_H  , LT(4, KC_J) , LT(2, KC_K)     , LT(6, KC_L)    , LSFT_T(KC_SCLN),
  KC_Z         , LCTL_T(KC_X) , LALT_T(KC_C) , KC_V        , KC_B  ,                               KC_N  , KC_M        , LALT_T(KC_COMM) , LCTL_T(KC_DOT) , KC_SLSH        ,
                                                             KC_P0 , KC_BSPC ,     LT(7, KC_SPC) , KC_P1
),

//    ┌───────────┬───────────┬───────────┬──────────┬──────┐                       ┌──────┬──────────┬───────────┬───────────┬───────────┐
//    │     q     │     w     │     e     │    r     │  t   │                       │  y   │    u     │     i     │     o     │     p     │
//    ├───────────┼───────────┼───────────┼──────────┼──────┤                       ├──────┼──────────┼───────────┼───────────┼───────────┤
//    │ LSFT_T(a) │ LT(5, s)  │ LT(1, d)  │ LT(3, f) │  g   │                       │  h   │ LT(4, j) │ LT(2, k)  │ LT(6, l)  │ LSFT_T(;) │
//    ├───────────┼───────────┼───────────┼──────────┼──────┤                       ├──────┼──────────┼───────────┼───────────┼───────────┤
//    │     z     │ LCTL_T(x) │ LALT_T(c) │    v     │  b   │                       │  n   │    m     │ LALT_T(,) │ LCTL_T(.) │     /     │
//    └───────────┴───────────┴───────────┴──────────┼──────┼──────┐   ┌────────────┼──────┼──────────┴───────────┴───────────┴───────────┘
//                                                   │ kp_0 │ bspc │   │ LT(7, spc) │ kp_1 │
//                                                   └──────┴──────┘   └────────────┴──────┘
[SYMBOLS] = LAYOUT_split_3x5_2(
  KC_Q         , KC_W         , KC_E         , KC_R        , KC_T  ,                               KC_Y  , KC_U        , KC_I            , KC_O           , KC_P           ,
  LSFT_T(KC_A) , LT(5, KC_S)  , LT(1, KC_D)  , LT(3, KC_F) , KC_G  ,                               KC_H  , LT(4, KC_J) , LT(2, KC_K)     , LT(6, KC_L)    , LSFT_T(KC_SCLN),
  KC_Z         , LCTL_T(KC_X) , LALT_T(KC_C) , KC_V        , KC_B  ,                               KC_N  , KC_M        , LALT_T(KC_COMM) , LCTL_T(KC_DOT) , KC_SLSH        ,
                                                             KC_P0 , KC_BSPC ,     LT(7, KC_SPC) , KC_P1
)
};

